-- 创建数据库
CREATE DATABASE notebook IF NOT EXISTS DEFAULT CHARACTER SET utf8;
-- 创建数据表
CREATE TABLE articles(id INT(8) NOT NULL AUTO_INCREMENT, title VARCHAR(255) DEFAULT,
            content TEXT, author varchar(255) DEFAULT NULL, create_date datetime DEFAULT NULL, PRIMARY KEY(id))
            ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE users(id INT(8) NOT NULL AUTO_INCREMENT, username VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL,
            password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))
            ENGINE=InnoDB DEFAULT CHARSET=utf8;